#include "onepixd.h"


static char *
xml_now(time_t now)
{
	char nowbuf[128];
	char *n;
	struct   tm *lt = NULL;
#if HAVE_LOCALTIME_R
	struct tm tm;
#else
	static pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER;
#endif

#if HAVE_LOCALTIME_R
        lt = localtime_r(&now, &tm);
#else
	(void) pthread_mutex_lock(&mutex);
	lt = localtime(&now);
#endif
	
	 (void) strftime(nowbuf, sizeof nowbuf, "%a, %d %b %Y %T GMT", lt);
#if ! HAVE_LOCALTIME_R
	(void) pthread_mutex_unlock(&mutex);
#endif

	 n = str_dup(nowbuf, __FILE__, __LINE__);
	return n;
}

void
xml_header(char *x, size_t xlen)
{
	time_t now;
	char * cp;

	if (x == NULL)
		return;

	now = time(NULL);
	(void) strlcat(x, "<?xml version=\"1.0\" encoding=\"us-ascii\" ?>\r\n", xlen);
	(void) strlcat(x, "<!-- generated by onepixd ", xlen);
	(void) strlcat(x, VERSION, xlen);
	(void) strlcat(x, " -->\r\n", xlen);
	(void) strlcat(x, "<data>\r\n", xlen);
	(void) strlcat(x, "<title>OnePixd Data Report</title>\r\n", xlen);
	(void) strlcat(x, "<language>en-us</language>\r\n", xlen);
	(void) strlcat(x, "<pubDate>", xlen);
	cp = xml_now(now);
	(void) strlcat(x, cp, xlen);
	(void) strlcat(x, "</pubDate>\r\n", xlen);

	cp = str_free(cp, __FILE__, __LINE__);
	return;
}

void
xml_trailer(char *x, size_t xlen)
{
	if (x == NULL)
		return;
	(void) strlcat(x, "</data>\r\n", xlen);
	return;
}

char *
xml_path_to_datetime(char *path)
{
	time_t date;

	if (path == NULL)
		return NULL;

	date = file_path_to_time(path);
	return xml_now(date);
}
